apiVersion: apps/v1
kind: Deployment
metadata:
  name: python-service
spec:
  replicas: { { .Values.pythonService.replicaCount } }
  selector:
    matchLabels:
      app: python-service
  template:
    metadata:
      labels:
        app: python-service
    spec:
      containers:
        - name: python-service
          image: "{{ .Values.pythonService.image.repository }}:{{ .Values.pythonService.image.tag }}"
          ports:
            - containerPort: 8000
